import sys
import re
import os
import sys

sourceFile = sys.argv[1]

# Read the ENTIRE g-code file into memory
with open(sourceFile, "r") as f:
    lines = f.read()

orca_sig = r'(; generated by OrcaSlicer(.*))'
lines = re.sub(orca_sig, r"; generated by SuperSlicer\2", lines)

with open(sourceFile, "w") as of:
    of.write(lines)
    
of.close()
f.close()